### ISSUE TITLE
CLI base project has type error

### ISSUE THREAD

**Issue by trifali** [moishinetzer/PBandJ#35]
I came across your project (and found it promising). I tried the starter command and notice type syntaxe error highlighting in vsCode. Not sure if this is knowns but here is a screenshot (stories/Button.stories):
<img width="786" alt="Screen Shot 2023-02-19 at 8 46 31 PM" src="https://user-images.githubusercontent.com/125521302/219990949-8944d928-d66b-4e31-bc43-71407df8f732.png">
EDIT: nevermind, it was my editor that needed to be restarted

**Comment by moishinetzer** [comment]
No problem! Feel free to open another issue to share your finished component library and I'll add it to the repo sample projects
