### ISSUE TITLE
Tailwindcss Integration

### ISSUE THREAD

**Issue by AlexMNet** [moishinetzer/PBandJ#36]
Hi Moishi, First off great job with this package! I'm really interested in integrating tailwindcss. How can we go about that?

**Comment by moishinetzer** [comment]
Hey Alex!

I'm still considering an extendable way to integrate Styling libraries (MUI, Tailwind etc.) 

For a (temporary) workaround, use tsup's inbuilt postcss integration; you can read up about it on their [documentation](https://tsup.egoist.dev/#css-support).

Follow this tailwind installation [tutorial](https://tailwindcss.com/docs/guides/vite), which was made for vite but works perfectly fine for any PBandJ library.

Make sure to import the CSS file with the tailwind directives into your main `index.ts` file, and for now, remove the `css-check` script in `package.json` (or even better, make it skip `index.ts`)

After doing this, everything _just works_ meaning you can publish your library, and users will have those styles shipped with it. 

> Note: those styles that tailwind generates will be shipped to the user, but it's unlikely they have their own `pb-3` class etc. So it should be completely fine to do so, in my opinion. But again, remember this caveat.

**Comment by AlexMNet** [comment]
@moishinetzer this is great! Thank you so much!

**Comment by enyelsequeira** [comment]
> Hey Alex!
> 
> I'm still considering an extendable way to integrate Styling libraries (MUI, Tailwind etc.)
> 
> For now, use tsup's inbuilt postcss integration; you can read up about it on their [documentation](https://tsup.egoist.dev/#css-support).
> 
> Follow this tailwind installation [tutorial](https://tailwindcss.com/docs/guides/vite), which was made for vite but works perfectly fine for any PBandJ library.
> 
> Make sure to import the CSS file with the tailwind directives into your main `index.ts` file, and for now, remove the `css-check` script in `package.json` (or even better, make it skip `index.ts`)
> 
> After doing this, everything _just works_ meaning you can publish your library, and users will have those styles shipped with it.
> 
> > Note: those styles that tailwind generates will be shipped to the user, but it's unlikely they have their own `pb-3` class etc. So it should be completely fine to do so, in my opinion. But again, remember this caveat.

Hello, I am wondering this, is there a way to integrate 2 different libraries, for example I myself want to use mantine and then tailwind, the tailwind part its simple, just wondering about mantine.dev

**Comment by moishinetzer** [comment]
Mantine is even easier than tailwind! Check this [quick example](https://github.com/moishinetzer/compwithmantinee) package I made. You can install it with

```sh
npm i compwithmantinee
```

It only exports a single component `Button`, and it works totally fine in any project. Make sure to wrap all exported components in the`MantineProvider` component

**Comment by AdonaiRdmeek** [comment]
That's great project to integrate with 👍

**Comment by Jared-Dahlke** [comment]
hey do you guys have an example repo with tailwind working? im trying to use this for a shadcn library but can't get the tailwind styles to apply

**Comment by Jared-Dahlke** [comment]
i ended up getting it to work by putting this into my tailwind.config.cjs in the consumer app, but this is not ideal to make every consumer app do this. preferably the consumer app would not have to have tailwind installed and can just import the css from the library 

```
const path = require('path');

const baseConfig = require('ui-comp2');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    path.join(path.dirname(require.resolve('ui-comp2')), '**/*.{js,cjs,mjs}')
  ],
  presets: [baseConfig]
};

```

any help is much appreciated.

**Comment by moishinetzer** [comment]
> Hey Alex!
> 
> I'm still considering an extendable way to integrate Styling libraries (MUI, Tailwind etc.)
> 
> For now, use tsup's inbuilt postcss integration; you can read up about it on their [documentation](https://tsup.egoist.dev/#css-support).
> 
> Follow this tailwind installation [tutorial](https://tailwindcss.com/docs/guides/vite), which was made for vite but works perfectly fine for any PBandJ library.
> 
> Make sure to import the CSS file with the tailwind directives into your main `index.ts` file, and for now, remove the `css-check` script in `package.json` (or even better, make it skip `index.ts`)
> 
> After doing this, everything _just works_ meaning you can publish your library, and users will have those styles shipped with it.
> 
> > Note: those styles that tailwind generates will be shipped to the user, but it's unlikely they have their own `pb-3` class etc. So it should be completely fine to do so, in my opinion. But again, remember this caveat.

@Jared-Dahlke Have you tried going through these steps? I was thinking about porting this to integrate just with shadcn/ui which I might do soon. Try following these steps and it really should just work.

**Comment by Jared-Dahlke** [comment]
Yes tried it multiple times . What folder should I initiate tailwind in? An example would be amazing if it really is that easy

**Comment by Jared-Dahlke** [comment]
@AlexMNet @AdonaiRdmeek  did you guys get this working? Do you mind posting an example?

**Comment by AlexMNet** [comment]
Hi @Jared-Dahlke sorry I actually didn't end up working with this as I had some other pressing projects to attend to.

**Comment by moishinetzer** [comment]
@Jared-Dahlke here is an example of implementing tailwindcss. Look at the diff between the init commit and the latest commit to see how I implemented it:

https://github.com/moishinetzer/pbandj-withtailwind

**Comment by Jared-Dahlke** [comment]
@moishinetzer how do i implement this?  I notice there is no .css file in /dist.

Should tailwind be installed in the consumer app?

**Comment by moishinetzer** [comment]
Well that's the beauty it's all injected when the package is imported. Please read through all the docs all of this is expanded there.

**Comment by Jared-Dahlke** [comment]
this works flawlessly. thank you!!!
